# Generated by Django 5.0.6 on 2026-06-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name="Rasmlar ro'yxati"),
        ),
    ]
