# Generated by Django 5.0.6 on 2026-06-29 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuitem_images'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Mijoz'), ('staff', 'Xodim')], default='customer', max_length=20, verbose_name='Yuboruvchi')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildi")),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.table', verbose_name='Stol')),
            ],
            options={
                'verbose_name': 'Stol xabari',
                'verbose_name_plural': 'Stol xabarlari',
                'ordering': ['created_at'],
            },
        ),
    ]
